# Generated by Django 4.1.7 on 2023-03-10 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_pic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="pic",
            field=models.ImageField(
                blank=True,
                default="img/user.png",
                null=True,
                upload_to="uploads/profile/",
            ),
        ),
    ]
