# Generated by Django 4.1.7 on 2023-02-28 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Notes", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mood", options={"verbose_name_plural": "Mood"},
        ),
        migrations.AlterModelOptions(
            name="notes", options={"verbose_name_plural": "Notes"},
        ),
        migrations.RenameField(model_name="mood", old_name="mode", new_name="mood",),
    ]
