# Generated by Django 4.1.7 on 2023-02-28 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Notes", "0002_alter_mood_options_alter_notes_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notes",
            name="user_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="mood", name="mood", field=models.CharField(max_length=20),
        ),
    ]
