# Generated by Django 4.1.7 on 2023-03-02 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Notes", "0003_notes_user_id_alter_mood_mood"),
    ]

    operations = [
        migrations.AddField(
            model_name="notes",
            name="date_created",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
